name: Fetch NVIDIA NIM Images

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  fetch-nim-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip

      - name: Install NGC CLI
        run: |

          curl -O https://ngc.nvidia.com/downloads/ngccli_linux.zip
          unzip ngccli_linux.zip -d $HOME/.ngc
          chmod +x $HOME/.ngc/ngc-cli/ngc
          # Append NGC CLI to PATH for subsequent steps
          echo "$HOME/.ngc/ngc-cli" >> $GITHUB_PATH

      - name: Authenticate with NGC
        env:
          NGC_API_KEY: ${{ secrets.NGC_API_KEY }}
        run: |
          ngc config set --apikey "$NGC_API_KEY"
          ngc config set --format_type json
          ngc config set --org "0628453927502513" 

      - name: Fetch and Filter NVIDIA NIM Images
        run: |
          ngc registry image list \
          | jq '[ .[] 
                  | select(any(.labels[]?.values[]?; . == "NVIDIA NIM")) ]
                | {
                    count: length,
                    displayNames: [.[].displayName]
                  }' > nim_images.json

      - name: Upload JSON Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nim-images
          path: nim_images.json
